services:
  app_server:
    container_name: app_server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_REGION=${AWS_REGION}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - DVC_REMOTE_URL=${DVC_REMOTE_URL}
      - MLFLOW_TRACKING_URI=http://ec2-54-173-194-157.compute-1.amazonaws.com:5000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend
    restart: unless-stopped
    # command: uvicorn server.api:app --host 0.0.0.0 --port 8000 --reload

volumes:
  app_data:

networks:
  backend:
    driver: bridge