search_space:
  max_depth: 
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
  learning_rate:
    min: 0.01
    max: 0.3
  n_estimators:
    - 50
    - 100
    - 150
    - 200
    - 250
    - 300
  subsample:
    min: 0.5
    max: 1.0
  colsample_bytree:
    min: 0.5
    max: 1.0
  gamma:
    min: 0
    max: 5
  reg_alpha:
    min: 0
    max: 1
  reg_lambda:
    min: 0
    max: 1